# 学生信息配置
username: 2110000000
password: i_love_thu
phone: 16666666666
bark: SqZPSeVtTSUCdrcnjWETYQ # 可选

# 全局配置
# 是否全自动化：请参照 README，判断是否可以做到
auto: true
totp_mode: 'shortcut' # TOTP验证模式：可选 "message"(通过转发短信来获取TOTP验证码) 或 "secret"(使用保存的密钥来获取TOTP验证码)，参见 README
totp_secret: '' # 当 totp_mode 为 "secret" 时需要配置此项，参见 README

# 预约配置列表
appointments:
    # 预约1：预约8月11日
    - yyrq: 20250811 # 预约日期，务必按照这个格式填写
      yyxm: 东南门 # 预约校门。（燕园：西南门 / 西侧门 / 东侧门 / 东南门 / 小东门 / 南门 / 万柳 / 畅春新园）（新燕园：东门 / 南门）
      yysj: 10:00 # 预约时间
      yysy: 游览 # 预约原因
      mode: 燕园 # 预约模式，可选 燕园 / 新燕园
      # 被预约人信息，数组，务必按照这个格式填写
      visitors:
          - name: 张三
            id: 110101200001011111
            phone: 11111111111
          - name: 李四
            id: 110101200002022222
            phone: 12222222222

    # 预约2：预约8月12日
    - yyrq: 20250812
      yyxm: 西南门
      yysj: 14:00
      yysy: 参观
      mode: 燕园
      visitors:
          - name: 王五
            id: 110101200003033333
            phone: 13333333333

    # 预约3：预约8月13日
    - yyrq: 20250813
      yyxm: 西侧门
      yysj: 09:00
      yysy: 办事
      mode: 燕园
      visitors:
          - name: 赵六
            id: 110101200004044444
            phone: 14444444444
